[workspace]
members = [
    "xtc",
    "piggy-bank",
#    History
    "xtc-history/xtc-history",
    "xtc-history/xtc-history-bucket",
    "xtc-history/xtc-history-common",
    "xtc-history/e2e",
]

[profile.release]
lto = true
opt-level = 'z'
overflow-checks = true

[profile.bench]
overflow-checks = true
